#!/bin/sh
set -e

APP=$(basename $(dirname "$(cd "$(dirname "$0")" && pwd)"))
APP_DIR=$(dirname "$(cd "$(dirname "$0")" && pwd)")
CONFIG="${APP_DIR}/config"
SHARED="$(dirname $APP_DIR)/shared"
CONFD="$SHARED/conf.d/"

if [[ ! -f "$CONFIG" ]]; then
  echo "Config is missing!"
  exit 1;
fi

source "$SHARED/config"
source "$CONFIG"

if [[ -z "$IMAGE" ]]; then
  echo "Image is not defined in the config!"
  exit 1;
fi

if [[ -z "$HOST" ]]; then
  echo "Host is not defined in the config!"
  exit 1;
fi

HOST="${HOST}.${SERVER}.${DOMAIN}.${TLD}"
RUN="docker run --restart always --name ${APP} -d -e TRUSTED_HOSTS=\"^(?:${HOST})$\" "
RUN="$RUN -e VIRTUAL_HOST=\"${HOST}\" -e LETSENCRYPT_HOST=\"${HOST}\" ${GT_ENV} ${GT_VOL}"

if [[ ! -z "$DB" ]]; then
  RUN="$RUN --link db:db"
  if [[ ! -z "$DB_USER" ]]; then
    RUN="$RUN -e DATABASE_URL=\"mysql://${DB_USER}:${DB_PASS}@db/${DB_NAME}\""
  fi
fi

RUN="$RUN $IMAGE" 

docker stop "$APP" || true
docker rm -f "$APP" || true
#docker rmi "$IMAGE"
eval $RUN

