#!/bin/sh
docker stop db
docker rm -f db
docker rmi mariadb:10.4
docker run --restart always \
        --name db \
	-e MYSQL_ROOT_PASSWORD=YOUR_ROOT_PASSWORD \
	-p 127.0.0.1:3306:3306 \
	-v /data/eu/db/data:/var/lib/mysql \
        -d \
        mariadb:10.4
